#!/usr/bin/env bash

BBAGENT_FIND_KEYS=${BBAGENT_FIND_KEYS:=find $HOME/.ssh/ -name "*.key" -type f}
BBAGENT_KEYS=$($BBAGENT_FIND_KEYS)
BBAGENT_ENV_FILE="$HOME/.agent-env"

[ -f $BBAGENT_ENV_FILE ] && source $BBAGENT_ENV_FILE

if [ -n "$BBAGENT_KEYS" ] ; then
    ssh-add -l &>/dev/null
    if [ "$?" != "0" ] ; then
        ssh-agent | grep -v "Agent pid" > $BBAGENT_ENV_FILE
        source $BBAGENT_ENV_FILE
    fi

    BBAGENT_ALREADY=$(ssh-add -l | cut -d" " -f3)

    for BBAGENT_KEY in $BBAGENT_KEYS ; do
        echo $BBAGENT_ALREADY | grep -q $BBAGENT_KEY || ssh-add $BBAGENT_KEY
    done

    unset BBAGENT_ALREADY
fi
